name: Sync Files

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '55 15 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: 准备完成
      uses: actions/checkout@v3

    - name: 下载压缩包
      run: |
        chmod +x $GITHUB_WORKSPACE/diy-scripts/*.sh
        $GITHUB_WORKSPACE/diy-scripts/sync-istoreos-files.sh

    - name: 自动发布资源到 Releases
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "iStoreosFile"
        name: "iStoreosFile"
        body: "iStoreosFile"
        files: /mnt/xiaomeng9597/files/*

    - name: 删除运行记录
      uses: xiaomeng9597/delete-workflow-runs@main
      with:
        retain_days: 20
        keep_minimum_runs: 15
        token: ${{ secrets.ACCESS_TOKEN }}
